version: '3.8'

services:
  mssql:
    image: dmitrukbohdan/library-mssql:v1
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: dmitrukbohdan/library-redis:v1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mssql_data:
  redis_data: