services:
  mssql:
    image: mcr.microsoft.com/mssql/server:latest  
    container_name: mssql_container
    environment:
      SA_PASSWORD: "pass1525"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"  
    networks:
      - library_network
    volumes:
      - mssql_data:/var/opt/mssql  

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: library_db  
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - library_network

  redis:
    image: redis:latest   
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  
    networks:
      - library_network
    command: ["redis-server", "--requirepass", "pass1525"]  

#   keycloak:
#     image: quay.io/keycloak/keycloak:latest  
#     container_name: keycloak_container
#     environment:
#       KEYCLOAK_ADMIN: admin  
#       KEYCLOAK_ADMIN_PASSWORD: admin
#       DB_VENDOR: h2  
#     ports:
#       - "8080:8080"  
#     networks:
#       library_network:
#         ipv4_address: 172.18.0.5

#   aspnet:
#     build:
#       context: ./path/to/aspnet  
#       dockerfile: Dockerfile
#     container_name: aspnet_container
#     depends_on:
#       - mssql  
#       - redis  
#     ports:
#       - "5000:5000"
#     networks:
#       library_network:
#         ipv4_address: 172.18.0.4


volumes:
  mssql_data: 
  postgres_data: 
  redis_data: 

networks:
  library_network:  
    driver: bridge

